
SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;599a15

IF @@ERROR <> 0 SET NOEXEC ON
BEGIN TRANSACTION

-- SQRIBE/TABLE;599a15
PRINT N'Add 2 rows to dbo.cmsContentVersion...'
GO -- SQRIBE/GO;599a15

SET IDENTITY_INSERT [dbo].[cmsContentVersion] ON
-- SQRIBE/INSERT;599a15
INSERT INTO [dbo].[cmsContentVersion] ([id],[ContentId],[VersionId],[VersionDate]) VALUES (1,1056,'03589414-A591-4D4F-B768-D173CB6BB772',CONVERT(datetime,'2018-11-05 14:18:43.433',121));
-- SQRIBE/INSERT;599a15
INSERT INTO [dbo].[cmsContentVersion] ([id],[ContentId],[VersionId],[VersionDate]) VALUES (2,1056,'B380CD3D-E090-43B4-AC2D-59DC1348C4F6',CONVERT(datetime,'2018-11-05 14:23:51.447',121));

IF @@ERROR <> 0 SET NOEXEC ON

COMMIT TRANSACTION

IF @@ERROR <> 0 SET NOEXEC ON

DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1) PRINT 'Restore table data dbo.cmsContentVersion succeeded'
ELSE BEGIN
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'Restore table data dbo.cmsContentVersion failed'
END

SET IDENTITY_INSERT [dbo].[cmsContentVersion] OFF
