
SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;599a15

IF @@ERROR <> 0 SET NOEXEC ON
BEGIN TRANSACTION

-- SQRIBE/TABLE;599a15
PRINT N'Add 3 rows to dbo.cmsDocumentType...'
GO -- SQRIBE/GO;599a15
-- SQRIBE/INSERT;599a15
INSERT INTO [dbo].[cmsDocumentType] ([contentTypeNodeId],[templateNodeId],[IsDefault]) VALUES (1059,1058,1);
-- SQRIBE/INSERT;599a15
INSERT INTO [dbo].[cmsDocumentType] ([contentTypeNodeId],[templateNodeId],[IsDefault]) VALUES (1063,1062,1);
-- SQRIBE/INSERT;599a15
INSERT INTO [dbo].[cmsDocumentType] ([contentTypeNodeId],[templateNodeId],[IsDefault]) VALUES (1065,1064,1);

IF @@ERROR <> 0 SET NOEXEC ON

COMMIT TRANSACTION

IF @@ERROR <> 0 SET NOEXEC ON

DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1) PRINT 'Restore table data dbo.cmsDocumentType succeeded'
ELSE BEGIN
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'Restore table data dbo.cmsDocumentType failed'
END
